# Generated by Django 5.2.3 on 2025-07-10 01:50

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Is this user a vendor?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Vendor approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_team',
            field=models.CharField(blank=True, help_text='F1 team this vendor represents', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[users.models.validate_file_size, users.models.validate_file_type]),
        ),
    ]
