# Generated by Django 5.2.3 on 2025-07-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_car_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_driver',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_f1_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='performance_style',
        ),
    ]
