# Generated by Django 5.2.3 on 2025-07-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_performance_and_f1_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
    ]
