# Generated by Django 5.2.3 on 2025-07-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='email_frequency',
        ),
    ]
