# Generated by Django 5.2.3 on 2025-07-20 01:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_email_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Address line 1 (5-255 characters)', max_length=255, validators=[users.models.validate_address]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Address line 2 (5-255 characters)', max_length=255, validators=[users.models.validate_address]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City name (max 100 characters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country name (max 100 characters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (10-15 digits)', max_length=20, validators=[users.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code (3-10 characters)', max_length=20, validators=[users.models.validate_postal_code]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State/province (max 100 characters)', max_length=100),
        ),
    ]
