# Generated by Django 5.2.3 on 2025-07-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='review',
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_helpful',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_verified_purchase',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
        migrations.DeleteModel(
            name='ReviewReport',
        ),
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
