# Generated by Django 5.2.3 on 2025-07-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_snapshot',
        ),
    ]
