# Generated by Django 5.2.3 on 2025-07-10 01:50

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productrating_rating'),
        ('users', '0002_userprofile_is_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_authentic_f1_part',
            field=models.BooleanField(default=False, help_text='Is this an authentic F1 part from a verified vendor?'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[products.models.validate_file_size, products.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[products.models.validate_file_size, products.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/', validators=[products.models.validate_file_size, products.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/additional/', validators=[products.models.validate_file_size, products.models.validate_file_type]),
        ),
    ]
