# Generated by Django 5.2.3 on 2025-07-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_authentic_f1_part_product_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compatible_cars',
        ),
    ]
