# Generated by Django 5.2.3 on 2025-07-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_compatible_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installation_difficulty',
        ),
    ]
