# Generated by Django 5.2.3 on 2025-07-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_installation_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='review',
        ),
    ]
