# Generated by Django 5.2.3 on 2025-07-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_review_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='performance_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_gain',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_savings',
        ),
    ]
