# Generated by Django 5.2.3 on 2025-07-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_performance_metrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
