# Generated by Django 5.2.3 on 2025-07-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
    ]
