# Generated by Django 5.2.3 on 2025-07-12 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
