# Generated by Django 5.2.3 on 2025-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_class",
            field=models.ImageField(
                blank=True,
                help_text="CSS class for category icon",
                max_length=50,
                upload_to="categories/",
            ),
        ),
    ]
