# Generated by Django 5.2.3 on 2025-07-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_contactmessage_alter_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
