# Generated by Django 5.2.3 on 2025-07-20 01:43

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit (auto-generated if not provided)', max_length=50, unique=True, validators=[products.models.validate_sku]),
        ),
    ]
